### ISSUE TITLE
[不是 BUG] 开黑啦 SDK 更新

### ISSUE THREAD

**Issue by TowardtheStars** [TISUnion/ChatBridge#22]
如题。虽然 khl.py 0.0.10 还可以正常使用，但是开黑啦所用库 khl.py 已更新到  0.2.3 版本。
目前插件对 khl.py 的 0.2.3 版本不兼容，显示找不到对象的错误

``` 
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".\ChatBridge.pyz\__main__.py", line 4, in <module>
  File ".\ChatBridge.pyz\chatbridge\cli_entry.py", line 43, in main
  File ".\ChatBridge.pyz\chatbridge\cli_entry.py", line 34, in kaiheila_bot
  File ".\ChatBridge.pyz\chatbridge\impl\kaiheila\entry.py", line 8, in <module>
ImportError: cannot import name 'Msg' from 'khl' (C:\Users\minecraft\AppData\Roaming\Python\Python37\site-packages\khl\__init__.py)
```

**Comment by Fallen-Breath** [comment]
这里是刻意使用 0.0.10 的 khl.py 的
