### ISSUE TITLE
cqhttp_bot无法启动

### ISSUE THREAD

**Issue by Glucy-2** [TISUnion/ChatBridge#24]
ChatBridge v2.2.0
py v3.9
已尝试过重装python websocket模块
启动输出（debian11, root与非root用户运行输出相同）：
````py
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/ChatBridge/ChatBridge.pyz/__main__.py", line 4, in <module>
  File "/opt/ChatBridge/ChatBridge.pyz/chatbridge/cli_entry.py", line 43, in main
  File "/opt/ChatBridge/ChatBridge.pyz/chatbridge/cli_entry.py", line 24, in cqhttp_bot
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/opt/ChatBridge/ChatBridge.pyz/chatbridge/impl/cqhttp/entry.py", line 34, in <module>
AttributeError: module 'websocket' has no attribute 'WebSocketApp'
````
`sudo pip install  websocket websocket-client --upgrade`输出：
````py
Looking in indexes: https://mirrors.tencent.com/pypi/simple
Requirement already satisfied: websocket in /usr/local/lib/python3.9/dist-packages (0.2.1)
/usr/share/python-wheels/urllib3-1.26.5-py2.py3-none-any.whl/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mirrors.tencent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Collecting websocket
  Using cached websocket-0.2.1-py3-none-any.whl
Requirement already satisfied: websocket-client in /usr/local/lib/python3.9/dist-packages (1.3.1)
/usr/share/python-wheels/urllib3-1.26.5-py2.py3-none-any.whl/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mirrors.tencent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Collecting websocket-client
/usr/share/python-wheels/urllib3-1.26.5-py2.py3-none-any.whl/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mirrors.tencent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Using cached https://mirrors.tencent.com/pypi/packages/35/21/8614b6de7c35d0bc584da13c45b8b08e404eee28a0504c1d00f5e1aa0a23/websocket_client-1.3.1-py3-none-any.whl (54 kB)
/usr/share/python-wheels/urllib3-1.26.5-py2.py3-none-any.whl/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mirrors.tencent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Using cached https://mirrors.tencent.com/pypi/packages/a9/fa/05ad1e899775e122da57d4b487ba62c92df251ccb54329a042a3b7d4ba5c/websocket_client-1.3.0-py3-none-any.whl (53 kB)
Requirement already satisfied: greenlet in /usr/local/lib/python3.9/dist-packages (from websocket) (1.1.2)
Requirement already satisfied: gevent in /usr/local/lib/python3.9/dist-packages (from websocket) (21.12.0)
Requirement already satisfied: zope.interface in /usr/local/lib/python3.9/dist-packages (from gevent->websocket) (5.4.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from gevent->websocket) (52.0.0)
Requirement already satisfied: zope.event in /usr/local/lib/python3.9/dist-packages (from gevent->websocket) (4.5.0)
````

**Comment by xrh0905** [comment]
https://github.com/AMWA-TV/nmos-testing/issues/133#issuecomment-713520831
