### ISSUE TITLE
无法创建bc服务器

### ISSUE THREAD

**Issue by HoShiNo-Estrella6066** [TISUnion/ChatBridge#43]
MCDR环境缺失，按照MCDR的指引安装之后显示如下，安装Crypto库后再次尝试，结果一致。

`D:\OneDrive\MC_Server\ChatBrige>python ChatBridge.pyz client
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\OneDrive\MC_Server\ChatBrige\ChatBridge.pyz\__main__.py", line 4, in <module>
  File "D:\OneDrive\MC_Server\ChatBrige\ChatBridge.pyz\chatbridge\cli_entry.py", line 48, in main
  File "D:\OneDrive\MC_Server\ChatBrige\ChatBridge.pyz\chatbridge\cli_entry.py", line 9, in client
  File "D:\OneDrive\MC_Server\ChatBrige\ChatBridge.pyz\chatbridge\impl\cli\cli_client.py", line 1, in <module>
  File "D:\OneDrive\MC_Server\ChatBrige\ChatBridge.pyz\chatbridge\core\client.py", line 14, in <module>
  File "D:\OneDrive\MC_Server\ChatBrige\ChatBridge.pyz\chatbridge\core\config.py", line 7, in <module>
  File "D:\OneDrive\MC_Server\ChatBrige\ChatBridge.pyz\chatbridge\core\network\basic.py", line 5, in <module>
  File "D:\OneDrive\MC_Server\ChatBrige\ChatBridge.pyz\chatbridge\core\network\cryptor.py", line 4, in <module>
ModuleNotFoundError: No module named 'Crypto'`

**Comment by Fallen-Breath** [comment]
依赖未完全安装导致的问题。请自行阅读 readme 解决
