### ISSUE TITLE
!!stats命令相关

### ISSUE THREAD

**Issue by yanxiatao** [TISUnion/ChatBridge#5]
使用stats查询时出现

Error running client survival
Traceback (most recent call last):
  File "plugins/ChatBridgeLibrary/ChatBridge_lib.py", line 341, in run
    self.processData(data)
  File "plugins/ChatBridgeLibrary/ChatBridge_lib.py", line 367, in processData
    self.on_recieve_command(js)
  File "plugins/ChatBridge_client.py", line 98, in on_recieve_command
    res_raw = stats.onServerInfo(None, None, command)
AttributeError: module 'StatsHelper' has no attribute 'onServerInfo'

**Comment by yanxiatao** [comment]
![image](https://user-images.githubusercontent.com/63758728/82135209-90011c00-9832-11ea-8e40-c71cdf73fd8e.png)

**Comment by Fallen-Breath** [comment]
更新ChatBridge_client

**Comment by yanxiatao** [comment]
好的谢谢qwq
